services:
  - type: web
    name: codemonfront
    env: node
    buildCommand: corepack prepare yarn@4.0.2 --activate && yarn install && yarn build:packages && yarn build:web
    startCommand: yarn workspace web start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://codemonbackend.onrender.com
